### ISSUE TITLE
add basic test

### ISSUE THREAD

**Issue by ltalirz** [marvel-nccr/ansible-role-aiidalab#10]
it would be great to add a basic test that makes sure the jupyter notebook server start up properly and the AiiDA lab homepage can be loaded (currently not tested).
Perhaps some of the machinery implemented by @csadorf for app tests can be reused here?

**Comment by csadorf** [comment]
@ltalirz Yes, it should be relatively easy to reuse that. If this is not an urgent then I can take a stab at it and please feel free to assign me the issue.

**Comment by ltalirz** [comment]
Great, thanks!
